baseURL = 'https://example.org/'
languageCode = 'ch-CN'
title = '且行且歌'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
